name: Deploy to GitHub Pages

on:
  push:
    branches: main

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'  # Use Node.js 21 as specified
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
          PUBLIC_HYGRAPH_URL: ${{ secrets.PUBLIC_HYGRAPH_URL }}  # Ensure these are secrets
          PUBLIC_HYGRAPH_KEY: ${{ secrets.PUBLIC_HYGRAPH_KEY }}
        run: |
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3  # Updated to v3

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v3  # Updated to v3
